// src/app/schemas/__init__.py
"""Pydantic schemas package."""
from src.app.schemas.common import (
    BaseSchema,
    PaginationParams,
    PaginatedResponse,
    ErrorResponse,
    ErrorDetail,
    SuccessResponse,
)
from src.app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserResponse,
    UserListResponse,
)
from src.app.schemas.auth import (
    Token,
    TokenData,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    ChangePasswordRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
)
from src.app.schemas.purchase_order import (
    PurchaseOrderLineBase,
    PurchaseOrderLineCreate,
    PurchaseOrderLineResponse,
    PurchaseOrderBase,
    PurchaseOrderCreate,
    PurchaseOrderUpdate,
    PurchaseOrderResponse,
    PurchaseOrderListResponse,
    PurchaseOrderSummary,
)
from src.app.schemas.invoice import (
    InvoiceLineBase,
    InvoiceLineCreate,
    InvoiceLineResponse,
    InvoiceBase,
    InvoiceCreate,
    InvoiceUpdate,
    InvoiceResponse,
    InvoiceListResponse,
    InvoiceSummary,
)
from src.app.schemas.delivery_note import (
    DeliveryNoteLineBase,
    DeliveryNoteLineCreate,
    DeliveryNoteLineResponse,
    DeliveryNoteBase,
    DeliveryNoteCreate,
    DeliveryNoteUpdate,
    DeliveryNoteResponse,
    DeliveryNoteListResponse,
    DeliveryNoteSummary,
)
from src.app.schemas.match import (
    MatchScore,
    MatchVariance,
    MatchResultBase,
    MatchResultCreate,
    MatchResultUpdate,
    MatchResultResponse,
    MatchResultWithDocuments,
    MatchConfirmationCreate,
    MatchConfirmationResponse,
    MatchResultListResponse,
    MatchSummary,
    MatchDecisionRequest,
    MatchDecisionResponse,
    CascadeMatchRequest,
    CascadeMatchResponse,
)

__all__ = [
    # Common
    "BaseSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "ErrorDetail",
    "SuccessResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserResponse",
    "UserListResponse",
    # Auth
    "Token",
    "TokenData",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "ChangePasswordRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    # Purchase Order
    "PurchaseOrderLineBase",
    "PurchaseOrderLineCreate",
    "PurchaseOrderLineResponse",
    "PurchaseOrderBase",
    "PurchaseOrderCreate",
    "PurchaseOrderUpdate",
    "PurchaseOrderResponse",
    "PurchaseOrderListResponse",
    "PurchaseOrderSummary",
    # Invoice
    "InvoiceLineBase",
    "InvoiceLineCreate",
    "InvoiceLineResponse",
    "InvoiceBase",
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceListResponse",
    "InvoiceSummary",
    # Delivery Note
    "DeliveryNoteLineBase",
    "DeliveryNoteLineCreate",
    "DeliveryNoteLineResponse",
    "DeliveryNoteBase",
    "DeliveryNoteCreate",
    "DeliveryNoteUpdate",
    "DeliveryNoteResponse",
    "DeliveryNoteListResponse",
    "DeliveryNoteSummary",
    # Match
    "MatchScore",
    "MatchVariance",
    "MatchResultBase",
    "MatchResultCreate",
    "MatchResultUpdate",
    "MatchResultResponse",
    "MatchResultWithDocuments",
    "MatchConfirmationCreate",
    "MatchConfirmationResponse",
    "MatchResultListResponse",
    "MatchSummary",
    "MatchDecisionRequest",
    "MatchDecisionResponse",
    "CascadeMatchRequest",
    "CascadeMatchResponse",
]
