// src/app/schemas/__init__.py
"""Schemas module initialization."""
from app.schemas.base import (
    BaseSchema,
    TimestampSchema,
    UUIDSchema,
    PaginationParams,
    PaginatedResponse,
    ErrorResponse,
    SuccessResponse,
)
from app.schemas.user import (
    UserCreate,
    UserUpdate,
    UserPasswordUpdate,
    UserResponse,
    UserBrief,
    Token,
    TokenPayload,
    LoginRequest,
    RefreshTokenRequest,
)
from app.schemas.supplier import (
    SupplierCreate,
    SupplierUpdate,
    SupplierResponse,
    SupplierBrief,
    SupplierListResponse,
)
from app.schemas.purchase_order import (
    PurchaseOrderLineCreate,
    PurchaseOrderLineUpdate,
    PurchaseOrderLineResponse,
    PurchaseOrderCreate,
    PurchaseOrderUpdate,
    PurchaseOrderResponse,
    PurchaseOrderBrief,
    PurchaseOrderListResponse,
    PurchaseOrderStatusUpdate,
)
from app.schemas.invoice import (
    InvoiceLineCreate,
    InvoiceLineUpdate,
    InvoiceLineResponse,
    InvoiceCreate,
    InvoiceUpdate,
    InvoiceResponse,
    InvoiceBrief,
    InvoiceListResponse,
    InvoiceStatusUpdate,
    InvoicePaymentUpdate,
)
from app.schemas.delivery_note import (
    DeliveryNoteLineCreate,
    DeliveryNoteLineUpdate,
    DeliveryNoteLineResponse,
    DeliveryNoteCreate,
    DeliveryNoteUpdate,
    DeliveryNoteResponse,
    DeliveryNoteBrief,
    DeliveryNoteListResponse,
)
from app.schemas.match import (
    MatchLineScore,
    MatchCreate,
    MatchResponse,
    MatchListResponse,
    MatchDecision,
    MatchSummary,
    MatchStatistics,
)
from app.schemas.balance import (
    BalanceLedgerCreate,
    BalanceLedgerUpdate,
    BalanceLedgerResponse,
    BalanceLedgerListResponse,
    BalanceSummary,
    BalanceApplication,
)

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "UUIDSchema",
    "PaginationParams",
    "PaginatedResponse",
    "ErrorResponse",
    "SuccessResponse",
    # User
    "UserCreate",
    "UserUpdate",
    "UserPasswordUpdate",
    "UserResponse",
    "UserBrief",
    "Token",
    "TokenPayload",
    "LoginRequest",
    "RefreshTokenRequest",
    # Supplier
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierResponse",
    "SupplierBrief",
    "SupplierListResponse",
    # Purchase Order
    "PurchaseOrderLineCreate",
    "PurchaseOrderLineUpdate",
    "PurchaseOrderLineResponse",
    "PurchaseOrderCreate",
    "PurchaseOrderUpdate",
    "PurchaseOrderResponse",
    "PurchaseOrderBrief",
    "PurchaseOrderListResponse",
    "PurchaseOrderStatusUpdate",
    # Invoice
    "InvoiceLineCreate",
    "InvoiceLineUpdate",
    "InvoiceLineResponse",
    "InvoiceCreate",
    "InvoiceUpdate",
    "InvoiceResponse",
    "InvoiceBrief",
    "InvoiceListResponse",
    "InvoiceStatusUpdate",
    "InvoicePaymentUpdate",
    # Delivery Note
    "DeliveryNoteLineCreate",
    "DeliveryNoteLineUpdate",
    "DeliveryNoteLineResponse",
    "DeliveryNoteCreate",
    "DeliveryNoteUpdate",
    "DeliveryNoteResponse",
    "DeliveryNoteBrief",
    "DeliveryNoteListResponse",
    # Match
    "MatchLineScore",
    "MatchCreate",
    "MatchResponse",
    "MatchListResponse",
    "MatchDecision",
    "MatchSummary",
    "MatchStatistics",
    # Balance
    "BalanceLedgerCreate",
    "BalanceLedgerUpdate",
    "BalanceLedgerResponse",
    "BalanceLedgerListResponse",
    "BalanceSummary",
    "BalanceApplication",
]
